name: CI

on: [push, pull_request]

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [16]
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: |
        npm install

    - name: Typechain
      run: |
        npm run typechain

    - name: Test & Coverage
      run: npm run coverage
    
    - uses: codecov/codecov-action@v2
      with:
        files: ./coverage.json
        name: codecov-check